---
- name: Install Keepalived
  apt:
    name: keepalived
    state: present

- name: Start Keepalived service
  service:
    name: keepalived
    state: started

- name: Enable Keepalived service
  service:
    name: keepalived
    enabled: yes

- name: Copy Keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
