all:
  hosts:
    web-1:
      ansible_host: 158.160.119.178
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    web-2:
      ansible_host: 158.160.111.206
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ha-1:
      ansible_host: 158.160.97.197
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ha-2:
      ansible_host: 158.160.117.35
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    webservers:
      hosts:
        web-1:
        web-2:
    loadbalancers:
      hosts:
        ha-1:
        ha-2:
