---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started

- name: Enable Nginx service
  service:
    name: nginx
    enabled: yes

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Copy index.html for Server 1
  copy:
    src: ../files/index1.html
    dest: /var/www/html/index.html
  when: "'web-1' in inventory_hostname"

- name: Copy index.html for Server 2
  copy:
    src: ../files/index2.html
    dest: /var/www/html/index.html
  when: "'web-2' in inventory_hostname"
