version: '3'

services:
  haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    ports:
      - "80:80"

  keepalived:
    build:
      context: ./keepalived
      dockerfile: Dockerfile
    container_name: keepalived
    networks:
      my_network:
        ipv4_address: 172.18.0.3

  web_server1:
    build:
      context: ./web_server1
      dockerfile: Dockerfile
    container_name: web_server1
    networks:
      my_network:
        ipv4_address: 172.18.0.4

  web_server2:
    build:
      context: ./web_server2
      dockerfile: Dockerfile
    container_name: web_server2
    networks:
      my_network:
        ipv4_address: 172.18.0.5

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
