FROM osixia/keepalived:2.0.20

COPY keepalived.conf /etc/keepalived/keepalived.conf

#CMD ["/usr/bin/keepalived", "--dont-fork", "--log-console", "--log-detail", "--dump-conf", "--log-facility", "7", "--vrrp"]
